<?php
/**
 * Where a picture may come from.
 *
 * @package AiCake
 */

declare( strict_types=1 );

namespace AiCake\Domain;

use AiCake\Support\Settings;

defined( 'ABSPATH' ) || exit;

/**
 * The four ways into the wizard, and which of them the shop currently offers
 * (D-054, D-059).
 *
 * **One place answers "is this source available?"** The wizard asks it to decide
 * what to draw, and every endpoint asks it before doing any work. Those two
 * must never be able to disagree — a card hidden from the page while the
 * endpoint still accepts it is not a switched-off feature, it is a switched-off
 * *button*, and this project has already shipped that mistake once with a WCFF
 * field a customer could answer themselves.
 *
 * The order here is the order the customer sees, and it is deliberate: cheapest
 * and most certain first, most expensive last.
 */
final class SourceCatalogue {

	/** Text on a blank sheet — no picture at all. */
	public const NONE = 'none';

	/** The customer's own photograph. */
	public const UPLOAD = 'upload';

	/** Generated by fal, and the only one that spends money per press. */
	public const AI = 'ai';

	/** Found by an image search (D-060). */
	public const SEARCH = 'search';

	/**
	 * Every source, in the order the wizard offers them.
	 *
	 * @return string[]
	 */
	public static function all(): array {
		return array( self::NONE, self::UPLOAD, self::AI, self::SEARCH );
	}

	/**
	 * The settings key that switches one on and off.
	 *
	 * @param string $source One of the constants.
	 */
	public static function setting_key( string $source ): string {
		return 'source_' . $source;
	}

	/**
	 * Is this a source at all?
	 *
	 * Separate from `enabled()` because the two failures are different and the
	 * customer should not be told the same thing for both: an unknown source is
	 * a broken client, a disabled one is a shop decision.
	 *
	 * @param string $source Candidate.
	 */
	public static function known( string $source ): bool {
		return in_array( $source, self::all(), true );
	}

	/**
	 * May the shop use this one right now?
	 *
	 * @param string   $source   One of the constants.
	 * @param Settings $settings Configuration.
	 */
	public static function enabled( string $source, Settings $settings ): bool {
		if ( ! self::known( $source ) ) {
			return false;
		}

		/*
		 * Search defaults off, everything else defaults on. The default lives
		 * here as well as in `Settings::defaults()` because `get()` is asked
		 * for a fallback, and a shop upgrading from a version that predates
		 * these keys has no stored value to read — without this, the upgrade
		 * would silently switch search *on*.
		 */
		$default = self::SEARCH !== $source;

		return (bool) $settings->get( self::setting_key( $source ), $default );
	}

	/**
	 * The sources the wizard should actually draw.
	 *
	 * @param Settings $settings Configuration.
	 * @return string[]
	 */
	public static function available( Settings $settings ): array {
		return array_values(
			array_filter(
				self::all(),
				static fn( string $source ): bool => self::enabled( $source, $settings )
			)
		);
	}

	/**
	 * Does this source produce a generated image the shop paid for?
	 *
	 * This is about **fal's invoice**, not about the customer's price. Since
	 * D-071 every source can carry a surcharge of its own, so the two questions
	 * have come apart: `search` costs the shop nothing and may still be priced
	 * above `none` if that is how the shop wants to sell it. This one keeps
	 * answering the first question — who spends money when the button is
	 * pressed — and the budget guard is its only caller.
	 *
	 * A function of the source rather than a stored flag, because a flag about
	 * whether money was spent is exactly the thing a browser must not be
	 * trusted with (D-044, D-058).
	 *
	 * @param string $source One of the constants.
	 */
	public static function costs_generation( string $source ): bool {
		return self::AI === $source;
	}

	/**
	 * The settings key holding what this source is called in Fields Factory.
	 *
	 * @param string $source One of the constants.
	 */
	public static function value_key( string $source ): string {
		return 'source_value_' . $source;
	}

	/**
	 * The Fields Factory field that prices where the picture came from.
	 *
	 * A setting, not a constant, for the same reason the four values are
	 * (D-071): WCFF resolves fields **by the label the admin typed**, and the
	 * label is also what the customer reads beside the answer on their order.
	 * So it is Ruslan's wording, and getting it wrong has to be fixable in
	 * wp-admin rather than in a deploy. `docs/wizard-v2.md` calls this field
	 * „Piešinio tipas"; the shipped default is „Paveikslėlio tipas", which
	 * matches the product's own name. Either is one settings box away.
	 */
	public const DEFAULT_FIELD_LABEL = 'Paveikslėlio tipas';

	/**
	 * What that field is called in this shop.
	 *
	 * @param Settings $settings Configuration.
	 */
	public static function field_label( Settings $settings ): string {
		$label = trim( (string) $settings->get( 'source_field_label', '' ) );

		return '' === $label ? self::DEFAULT_FIELD_LABEL : $label;
	}

	/**
	 * What the shop calls this source where it is priced (D-071).
	 *
	 * The string posted as the „Paveikslėlio tipas" radio, which WCFF matches
	 * its price rule against and then writes on the order and into the e-mail.
	 * So it is both a key and a sentence the customer reads, which is why it
	 * lives in settings and not in a `__()` call: a translation layer between
	 * our value and the shop's typed choice is a mismatch waiting to happen,
	 * and the mismatch is silent — base price, and nothing on the order.
	 *
	 * Falls back to the source key rather than to an empty string. A field
	 * whose choices nobody configured then shows `upload` on the order, which
	 * is wrong in a way somebody notices, instead of showing nothing at all.
	 *
	 * @param string   $source   One of the constants.
	 * @param Settings $settings Configuration.
	 */
	public static function field_value( string $source, Settings $settings ): string {
		if ( ! self::known( $source ) ) {
			return '';
		}

		$value = trim( (string) $settings->get( self::value_key( $source ), '' ) );

		return '' === $value ? $source : $value;
	}

	/**
	 * What the customer reads on the card.
	 *
	 * @param string $source One of the constants.
	 * @return array{title: string, note: string}
	 */
	public static function copy( string $source ): array {
		switch ( $source ) {
			case self::NONE:
				return array(
					'title' => __( 'Tik užrašas', 'ai-cake-topper' ),
					'note'  => __( 'Be paveikslėlio — tik jūsų tekstas.', 'ai-cake-topper' ),
				);

			case self::UPLOAD:
				return array(
					'title' => __( 'Mano nuotrauka', 'ai-cake-topper' ),
					'note'  => __( 'Įkelkite savo nuotrauką ir išsikirpkite reikiamą vietą.', 'ai-cake-topper' ),
				);

			case self::SEARCH:
				return array(
					'title' => __( 'Rasti internete', 'ai-cake-topper' ),
					'note'  => __( 'Aprašykite, ko ieškote, ir rinkitės iš rastų paveikslėlių.', 'ai-cake-topper' ),
				);

			case self::AI:
			default:
				return array(
					'title' => __( 'Sukurti su AI', 'ai-cake-topper' ),
					'note'  => __( 'Aprašykite lietuviškai — piešinį sukurs dirbtinis intelektas.', 'ai-cake-topper' ),
				);
		}
	}
}
